# Generated by Django 4.2.28 on 2026-03-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuser_role_supervisorprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('student_mobile', models.CharField(max_length=15)),
                ('room_no', models.CharField(max_length=10)),
                ('hostel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=100)),
                ('supervisor_mobile', models.CharField(max_length=15)),
                ('location', models.CharField(choices=[('kutir', 'Kutir'), ('postoffice', 'Post Office')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='status',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='home.student'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.supervisor'),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='SupervisorProfile',
        ),
    ]
