# Generated by Django 4.2.28 on 2026-03-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_supervisor_remove_supervisorprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='unknown@banasthali.in', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_year',
            field=models.IntegerField(default=1),
        ),
    ]
