# Generated by Django 4.2.28 on 2026-03-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_student_student_department_student_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='expected_date',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='parcel',
            name='hostel',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='parcel',
            name='room_no',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='parcel',
            name='student_mobile',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='parcel',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
