# Generated by Django 4.2.28 on 2026-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_parcel_expected_date_remove_parcel_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_id', models.CharField(max_length=20, unique=True)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('supervisor_email', models.EmailField(default='unknown@banasthali.in', max_length=254, unique=True)),
                ('supervisor_location', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor')], max_length=20),
        ),
    ]
