# Generated by Django 4.2.28 on 2026-03-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student_user_supervisor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(default='Received', max_length=50),
        ),
    ]
