# Generated by Django 4.2.28 on 2026-03-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_parcel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='home.student'),
        ),
    ]
