# Generated by Django 4.2.28 on 2026-03-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_parcel_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_btbt', models.CharField(blank=True, max_length=20)),
                ('rating', models.IntegerField()),
                ('feedback_type', models.CharField(choices=[('service', 'Service Quality'), ('delivery', 'Delivery Experience'), ('app', 'App/Website'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('contact_me', models.BooleanField(default=False)),
                ('anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
