# Generated by Django 4.2.28 on 2026-03-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='source',
            field=models.CharField(choices=[('kutir', 'Kutir'), ('postoffice', 'Post Office')], default='kutir', max_length=20),
        ),
    ]
