# Generated by Django 4.2.28 on 2026-03-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_parcel_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('parcel_added', 'Parcel Added'), ('status_update', 'Status Update'), ('feedback', 'Feedback'), ('alert', 'Alert')], default='parcel_added', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='home.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
