# Generated by Django 4.2.28 on 2026-03-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('parcel_added', 'Parcel Added'), ('status_update', 'Status Update'), ('supervisor_added', 'Supervisor Added'), ('supervisor_deleted', 'Supervisor Deleted')], default='parcel_added', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default='kutir', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
